//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public string LogName { get; set; }
        public string LogNote { get; set; }
        public Nullable<System.DateTime> LogCreatTime { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
