//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1891
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastElite.SMS.Manage {
    
    public partial class RoleDetail {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected System.Web.UI.WebControls.DropDownList RoleTypeList;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
        protected System.Web.UI.WebControls.TextBox Name1;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox Note1;
        protected System.Web.UI.WebControls.ImageButton InsertButton;
        protected System.Web.UI.WebControls.ImageButton CancelButton;
    }
}
