//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int Code { get; set; }
        public string oaName { get; set; }
        public string link { get; set; }
        public Nullable<int> sort { get; set; }
        public string img { get; set; }
        public Nullable<int> State { get; set; }
    }
}
